// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyQuanCaPhe.Data;

#nullable disable

namespace QuanLyQuanCaPhe.Migrations
{
    [DbContext(typeof(CaPheDbContext))]
    [Migration("20260412180556_SoftDeleteLoaiMonAndStopSellingDelete")]
    partial class SoftDeleteLoaiMonAndStopSellingDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtHoaDon_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("MonID")
                        .HasColumnType("int");

                    b.Property<short>("SoLuongBan")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("MonID");

                    b.HasIndex("HoaDonID", "MonID")
                        .HasDatabaseName("IX_HoaDonChiTiet_HoaDonID_MonID");

                    b.ToTable("HoaDon_ChiTiet", null, t =>
                        {
                            t.HasCheckConstraint("CK_HoaDonChiTiet_SoLuongBan", "[SoLuongBan] > 0");
                        });
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityName", "EntityId", "CreatedAt");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaBan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_Ban_TrangThai");

                    b.ToTable("Ban", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ban_TrangThai", "[TrangThai] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaCongThucMon", b =>
                {
                    b.Property<int>("MonID")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuID")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("MonID", "NguyenLieuID");

                    b.HasIndex("NguyenLieuID");

                    b.ToTable("CongThucMon", null, t =>
                        {
                            t.HasCheckConstraint("CK_CongThucMon_SoLuong", "[SoLuong] > 0");
                        });
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaHoadon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BanID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("Khách lẻ");

                    b.Property<string>("GhiChuHoaDon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.HasIndex("BanID")
                        .IsUnique()
                        .HasDatabaseName("UX_HoaDon_Ban_Mo")
                        .HasFilter("[TrangThai] = 0");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("NgayLap", "TrangThai")
                        .HasDatabaseName("IX_HoaDon_NgayLap_TrangThai");

                    b.HasIndex("TrangThai", "NhanVienID", "NgayLap")
                        .HasDatabaseName("IX_HoaDon_TrangThai_NhanVien_NgayLap");

                    b.ToTable("HoaDon", null, t =>
                        {
                            t.HasCheckConstraint("CK_HoaDon_TrangThai", "[TrangThai] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaKhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ID");

                    b.HasIndex("IsDeleted");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaLoaiMon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("IsDeleted");

                    b.ToTable("LoaiMon", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaMon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LoaiMonID")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TrangThaiTextLegacy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang kinh doanh")
                        .HasColumnName("TrangThaiText_Legacy");

                    b.HasKey("ID");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LoaiMonID");

                    b.ToTable("Mon", null, t =>
                        {
                            t.HasCheckConstraint("CK_Mon_TrangThai", "[TrangThai] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaNguyenLieu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaNhapGanNhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MucCanhBao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongTon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TrangThaiTextLegacy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThaiText_Legacy");

                    b.HasKey("ID");

                    b.ToTable("NguyenLieu", null, t =>
                        {
                            t.HasCheckConstraint("CK_NguyenLieu_TrangThai", "[TrangThai] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaNhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ID");

                    b.HasIndex("IsDeleted");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaPermission", b =>
                {
                    b.Property<int>("VaiTroID")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<string>("Feature")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Feature");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit")
                        .HasColumnName("CanCreate");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit")
                        .HasColumnName("CanDelete");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("CanUpdate");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit")
                        .HasColumnName("CanView");

                    b.HasKey("VaiTroID", "Feature");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaPhieuNhapKho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguyenLieuID")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuongNhap")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("NguyenLieuID");

                    b.ToTable("PhieuNhapKho", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaPhieuXuatKho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("NguyenLieuID")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuongXuat")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("ID");

                    b.HasIndex("NguyenLieuID", "NgayXuat");

                    b.ToTable("PhieuXuatKho", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhieuXuatKho_SoLuongXuat", "[SoLuongXuat] > 0");
                        });
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("HoatDong")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int")
                        .HasColumnName("NhanVienId");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Username");

                    b.Property<int>("VaiTroID")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.HasIndex("VaiTroID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaVaiTro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtHoaDon_ChiTiet", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaHoadon", "HoaDon")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaMon", "Mon")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("MonID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Mon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaCongThucMon", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaMon", "Mon")
                        .WithMany("CongThucMon")
                        .HasForeignKey("MonID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaNguyenLieu", "NguyenLieu")
                        .WithMany("CongThucMon")
                        .HasForeignKey("NguyenLieuID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mon");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaHoadon", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaBan", "Ban")
                        .WithMany("HoaDon")
                        .HasForeignKey("BanID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaKhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaNhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaMon", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaLoaiMon", "LoaiMon")
                        .WithMany("Mon")
                        .HasForeignKey("LoaiMonID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoaiMon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaPermission", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaVaiTro", "VaiTro")
                        .WithMany("Permissions")
                        .HasForeignKey("VaiTroID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaPhieuNhapKho", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaNguyenLieu", "NguyenLieu")
                        .WithMany("PhieuNhapKho")
                        .HasForeignKey("NguyenLieuID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaPhieuXuatKho", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaNguyenLieu", "NguyenLieu")
                        .WithMany("PhieuXuatKho")
                        .HasForeignKey("NguyenLieuID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaUser", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaNhanVien", "NhanVien")
                        .WithOne("User")
                        .HasForeignKey("QuanLyQuanCaPhe.Data.dtaUser", "NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaVaiTro", "VaiTro")
                        .WithMany("Users")
                        .HasForeignKey("VaiTroID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaBan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaHoadon", b =>
                {
                    b.Navigation("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaKhachHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaLoaiMon", b =>
                {
                    b.Navigation("Mon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaMon", b =>
                {
                    b.Navigation("CongThucMon");

                    b.Navigation("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaNguyenLieu", b =>
                {
                    b.Navigation("CongThucMon");

                    b.Navigation("PhieuNhapKho");

                    b.Navigation("PhieuXuatKho");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaNhanVien", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaVaiTro", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
